In [1]:
import pandas as pd
import numpy as np
import joblib
import sys

try:
    
    input_predictors = pd.read_csv("train_features.csv")
    input_predictors = input_predictors.drop([input_predictors.columns[0]], axis=1)
    
    user_info = {}

    model_name = input("Enter Model Name: ")
    model, scaler = joblib.load(model_name)
    
    #print(f"Put in all features, comma separated: {','.join(list(input_predictors.columns))}")
    features = input().replace(" ","").split(",")
    user_info_df = pd.DataFrame(data=[features], index = None, columns=input_predictors.columns)
    user_info_df = user_info_df.astype(np.float64)
    display(user_info_df.T)
    user_info_df = scaler.transform(user_info_df)
    povertyclass = model.predict(user_info_df)
    print(int(povertyclass[0]))
    #print(user_info_df.dtypes)
    
except IOError as e:

    print("Error: Unable to find the specified model!")

Enter Model Name: randomforest.pkl
1,3,0,1,2,3,0,0,0,0,0,0,0,1,3,0.75,0.0,4.5,3.5,0,4,1,1.0,1.0,1.0

                    0
hacdor           1.00
rooms            3.00
v18q             0.00
r4h1             1.00
r4m1             2.00
r4t1             3.00
escolari         0.00
paredblolad      0.00
paredmad         0.00
pisomoscer       0.00
cielorazo        0.00
energcocinar2    0.00
energcocinar4    0.00
elimbasu1        1.00
hogar_nin        3.00
dependency       0.75
edjefe           0.00
meaneduc         4.50
overcrowding     3.50
computer         0.00
qmobilephone     4.00
lugar1           1.00
wall_condition   1.00
roof_condition   1.00
floor_condition  1.00

2